/**
 * MAISHAA WORKSPACE — Creative Templates & Official Brand Kit
 * Professional editable vector templates for Certificates, ID Cards, Social Media, Posters, and Flyers.
 */

import { BrandKit, DesignTemplate, CanvasElement, DesignPage } from '../types/creativeSuite';

export const MAISHAA_BRAND_KIT: BrandKit = {
  name: 'MAISHAA WORKSPACE Official Brand Kit',
  palette: {
    primary: '#0B192C',
    secondary: '#2563EB',
    teal: '#0D9488',
    gold: '#F59E0B',
    surface: '#F8FAFC',
    dark: '#070E1E',
  },
  fonts: {
    headingBn: 'SolaimanLipi, "Noto Sans Bengali", sans-serif',
    bodyBn: 'SolaimanLipi, "Noto Sans Bengali", sans-serif',
    headingEn: 'Inter, system-ui, sans-serif',
    bodyEn: 'Inter, system-ui, sans-serif',
  },
  logoUrl: '/favicon.svg',
};

export const CREATIVE_TEMPLATES: DesignTemplate[] = [
  // 1. Official Certificate Template (Bangla & English with Bulk Create keys)
  {
    id: 'cert_academic_honor',
    nameEn: 'Certificate of Achievement & Honor',
    nameBn: 'সম্মাননা ও কৃতিত্বের সনদপত্র',
    category: 'certificate',
    width: 800,
    height: 566, // Standard landscape A4 aspect ratio
    thumbnailColor: '#0B192C',
    pages: [
      {
        id: 'p1',
        name: 'Certificate Front',
        width: 800,
        height: 566,
        background: {
          type: 'solid',
          color: '#FFFFFF',
        },
        elements: [
          // Outer border frame
          {
            id: 'border_outer',
            type: 'shape',
            shapeType: 'rect',
            x: 24,
            y: 24,
            width: 752,
            height: 518,
            rotation: 0,
            opacity: 1,
            locked: true,
            visible: true,
            zIndex: 1,
            fill: '#FFFFFF',
            stroke: '#0B192C',
            strokeWidth: 4,
          },
          // Inner gold accent frame
          {
            id: 'border_inner',
            type: 'shape',
            shapeType: 'rect',
            x: 32,
            y: 32,
            width: 736,
            height: 502,
            rotation: 0,
            opacity: 1,
            locked: true,
            visible: true,
            zIndex: 2,
            fill: 'transparent',
            stroke: '#F59E0B',
            strokeWidth: 2,
          },
          // Header title
          {
            id: 'header_sub',
            type: 'text',
            text: 'গণপ্রজাতন্ত্রী বাংলাদেশ সরকার অনুমোদিত প্রতিষ্ঠান',
            x: 200,
            y: 56,
            width: 400,
            height: 24,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 3,
            fontSize: 13,
            color: '#475569',
            textAlign: 'center',
            fontWeight: 'normal',
          },
          {
            id: 'header_main',
            type: 'text',
            text: 'CERTIFICATE OF ACHIEVEMENT',
            x: 100,
            y: 84,
            width: 600,
            height: 40,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 4,
            fontSize: 26,
            color: '#0B192C',
            textAlign: 'center',
            fontWeight: 'bold',
            letterSpacing: 2,
          },
          {
            id: 'presented_to',
            type: 'text',
            text: 'এই প্রত্যয়নপত্রটি অত্যন্ত গৌরবের সাথে প্রদান করা হলো',
            x: 150,
            y: 140,
            width: 500,
            height: 28,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 5,
            fontSize: 15,
            color: '#334155',
            textAlign: 'center',
          },
          // Recipient Name (Bulk Create Bind Key: {{Name}})
          {
            id: 'recipient_name',
            type: 'text',
            text: 'ফারজানা ইসলাম দিনা',
            x: 100,
            y: 180,
            width: 600,
            height: 50,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 6,
            fontSize: 32,
            color: '#2563EB',
            textAlign: 'center',
            fontWeight: 'bold',
            bindKey: 'Name',
          },
          // Award reason (Bulk Create Bind Key: {{Course}})
          {
            id: 'cert_reason',
            type: 'text',
            text: 'সফলতার সাথে তথ্যপ্রযুক্তি ও ডিজিটাল অফিস ম্যানেজমেন্ট কোর্স সম্পন্ন করায়।',
            x: 120,
            y: 250,
            width: 560,
            height: 48,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 7,
            fontSize: 15,
            color: '#1E293B',
            textAlign: 'center',
            bindKey: 'Course',
          },
          // Signature left
          {
            id: 'sig_date',
            type: 'text',
            text: '১৬ ফেব্রুয়ারি ২০২৬\nতারিখ',
            x: 100,
            y: 430,
            width: 200,
            height: 44,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 8,
            fontSize: 13,
            color: '#475569',
            textAlign: 'center',
            bindKey: 'Date',
          },
          // Signature right
          {
            id: 'sig_author',
            type: 'text',
            text: 'পরিচালক / অধ্যক্ষ\nমায়িশা ডিজিটাল ইন্সটিটিউট',
            x: 500,
            y: 430,
            width: 200,
            height: 44,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 9,
            fontSize: 13,
            color: '#475569',
            textAlign: 'center',
          },
          // Seal / Badge
          {
            id: 'badge_seal',
            type: 'shape',
            shapeType: 'circle',
            x: 360,
            y: 410,
            width: 80,
            height: 80,
            rotation: 0,
            opacity: 1,
            locked: true,
            visible: true,
            zIndex: 10,
            fill: '#F59E0B',
            stroke: '#B45309',
            strokeWidth: 3,
          },
          {
            id: 'badge_text',
            type: 'text',
            text: 'OFFICIAL\nSEAL',
            x: 360,
            y: 432,
            width: 80,
            height: 36,
            rotation: 0,
            opacity: 1,
            locked: true,
            visible: true,
            zIndex: 11,
            fontSize: 11,
            color: '#FFFFFF',
            textAlign: 'center',
            fontWeight: 'bold',
          },
        ],
      },
    ],
  },

  // 2. Official Student / Employee ID Card Template
  {
    id: 'id_card_professional',
    nameEn: 'Corporate & Student Identity Card',
    nameBn: 'স্মার্ট পরিচয়পত্র (ID Card)',
    category: 'id_card',
    width: 360,
    height: 540, // Standard CR80 portrait ratio
    thumbnailColor: '#2563EB',
    pages: [
      {
        id: 'id_p1',
        name: 'ID Card Front',
        width: 360,
        height: 540,
        background: {
          type: 'solid',
          color: '#FFFFFF',
        },
        elements: [
          // Top header band
          {
            id: 'top_band',
            type: 'shape',
            shapeType: 'rect',
            x: 0,
            y: 0,
            width: 360,
            height: 120,
            rotation: 0,
            opacity: 1,
            locked: true,
            visible: true,
            zIndex: 1,
            fill: '#0B192C',
          },
          // Organization text
          {
            id: 'org_name',
            type: 'text',
            text: 'MAISHAA DIGITAL WORKSPACE',
            x: 20,
            y: 28,
            width: 320,
            height: 24,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 2,
            fontSize: 16,
            color: '#FFFFFF',
            textAlign: 'center',
            fontWeight: 'bold',
          },
          {
            id: 'id_type',
            type: 'text',
            text: 'IDENTITY CARD • পরিচয়পত্র',
            x: 20,
            y: 56,
            width: 320,
            height: 20,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 3,
            fontSize: 12,
            color: '#38BDF8',
            textAlign: 'center',
            fontWeight: '600',
          },
          // Photo box frame (Bulk Create Bind Key: {{Photo}})
          {
            id: 'photo_box',
            type: 'shape',
            shapeType: 'rect',
            x: 110,
            y: 90,
            width: 140,
            height: 150,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 4,
            fill: '#E2E8F0',
            stroke: '#FFFFFF',
            strokeWidth: 4,
            borderRadius: 8,
          },
          // Name (Bulk Create Bind Key: {{Name}})
          {
            id: 'id_name',
            type: 'text',
            text: 'ফারজানা ইসলাম দিনা',
            x: 20,
            y: 260,
            width: 320,
            height: 32,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 5,
            fontSize: 20,
            color: '#0F172A',
            textAlign: 'center',
            fontWeight: 'bold',
            bindKey: 'Name',
          },
          // Designation (Bulk Create Bind Key: {{Role}})
          {
            id: 'id_role',
            type: 'text',
            text: 'সফটওয়্যার কোয়ালিটি ইঞ্জিনিয়ার',
            x: 20,
            y: 295,
            width: 320,
            height: 22,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 6,
            fontSize: 13,
            color: '#2563EB',
            textAlign: 'center',
            fontWeight: '600',
            bindKey: 'Role',
          },
          // ID Number & Blood Group (Bulk Create Bind Key: {{ID}})
          {
            id: 'id_details',
            type: 'text',
            text: 'ID NO: MSH-2026-9814\nBLOOD GROUP: B (+ve)\nVALID THRU: 12/2028',
            x: 40,
            y: 340,
            width: 280,
            height: 70,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 7,
            fontSize: 13,
            color: '#334155',
            textAlign: 'center',
            lineHeight: 1.5,
            bindKey: 'ID',
          },
          // Bottom teal bar
          {
            id: 'bottom_bar',
            type: 'shape',
            shapeType: 'rect',
            x: 0,
            y: 510,
            width: 360,
            height: 30,
            rotation: 0,
            opacity: 1,
            locked: true,
            visible: true,
            zIndex: 8,
            fill: '#0D9488',
          },
        ],
      },
    ],
  },

  // 3. Social Media Modern Post (1080x1080 Square)
  {
    id: 'social_square_promo',
    nameEn: 'Social Media Modern Promotional Post',
    nameBn: 'সোশ্যাল মিডিয়া ডিজিটাল প্রমো ব্যানার',
    category: 'social',
    width: 600,
    height: 600,
    thumbnailColor: '#0D9488',
    pages: [
      {
        id: 'soc_p1',
        name: 'Square Post',
        width: 600,
        height: 600,
        background: {
          type: 'solid',
          color: '#070E1E',
        },
        elements: [
          // Background soft accent blob
          {
            id: 'blob_1',
            type: 'shape',
            shapeType: 'circle',
            x: 350,
            y: -50,
            width: 300,
            height: 300,
            rotation: 0,
            opacity: 0.25,
            locked: true,
            visible: true,
            zIndex: 1,
            fill: '#2563EB',
          },
          {
            id: 'badge_promo',
            type: 'text',
            text: 'SPECIAL WORKSHOP • বিশেষ কর্মশালা',
            x: 40,
            y: 60,
            width: 360,
            height: 24,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 2,
            fontSize: 13,
            color: '#2DD4BF',
            fontWeight: 'bold',
          },
          {
            id: 'headline_main',
            type: 'text',
            text: 'মডার্ন অফিস অটোমেশন ও\nপ্রফেশনাল ডকুমেন্ট ম্যানেজমেন্ট',
            x: 40,
            y: 96,
            width: 520,
            height: 100,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 3,
            fontSize: 28,
            color: '#FFFFFF',
            fontWeight: 'bold',
            lineHeight: 1.3,
          },
          {
            id: 'desc_text',
            type: 'text',
            text: 'পিডিএফ এডিটিং, এক্সেল ডেটা ম্যানেজমেন্ট এবং বাংলা টাইপোগ্রাফির সব আধুনিক কৌশল শিখুন এক কর্মশালায়।',
            x: 40,
            y: 220,
            width: 520,
            height: 60,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 4,
            fontSize: 15,
            color: '#94A3B8',
            lineHeight: 1.4,
          },
          // Button call to action
          {
            id: 'cta_box',
            type: 'shape',
            shapeType: 'rect',
            x: 40,
            y: 480,
            width: 220,
            height: 52,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 5,
            fill: '#2563EB',
            borderRadius: 12,
          },
          {
            id: 'cta_text',
            type: 'text',
            text: 'রেজিস্ট্রেশন করুন →',
            x: 40,
            y: 494,
            width: 220,
            height: 28,
            rotation: 0,
            opacity: 1,
            locked: false,
            visible: true,
            zIndex: 6,
            fontSize: 16,
            color: '#FFFFFF',
            textAlign: 'center',
            fontWeight: 'bold',
          },
        ],
      },
    ],
  },
];
